import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import FeedbackList from '../components/FeedbackList'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import Sidebar from '../components/Sidebar'
import MainLayout from '../layouts/MainLayout'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Feedback APP</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&family=Roboto:wght@300&display=swap" rel="stylesheet"></link>
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Sidebar />
      <main>
        <Navbar />
        <FeedbackList />
      </main>


    <Footer/>
    </div>
  )
}

export default Home
